version: '3.1'

services:
  pubsub:
    image: knarz/pubsub-emulator
    restart: always
    ports:
      - 8085:8085
  db:
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_USER: oauth
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
  ## Uncomment the lines below to also run the oauth service as part of docker-compose. Useful for local dev/testing
  # oauth:
  #   build:
  #     dockerfile: ../dist/Dockerfile
  #     context: ../
  #     args:
  #       NPM_TOKEN: $NPM_TOKEN
  #   image: gcr.io./koda-software/oauth:local