version: '1.0'

steps:
  clone:
    type: git-clone
    title: Clone project
    description: Cloning project from source repository
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: ${{CF_BRANCH}}
    git: github
    stage: clone
  build:
    type: build
    title: Build
    description: Building docker image
    working_directory: ${{clone}}
    dockerfile: dist/Dockerfile
    image_name: ${{OWNER}}/${{IMAGE}}
    tag: ${{VERSION}}
    registry: koda-software
    stage: build
  test:
    title: Test
    image: node:10.17
    description: Running application tests
    working_directory: ${{clone}}
    stage: test
    commands:
      - cd app
      - npm i
      - NODE_ENV=test npx knex migrate:latest
      - npm t
    services:
      composition:
        pubsub:
          image: google/cloud-sdk
          command: gcloud components install pubsub-emulator && gcloud components update && gcloud beta emulators pubsub start
          ports:
            - 8085
  publish:
    type: push
    title: Publish
    description: Publish docker image
    candidate: ${{build}}
    tag: "$(cat package.json | grep '\"version\":' | sed -e 's/  \"version\": \"//' | sed -e 's/\",//')"
    registry: koda-software
    stage: publish

stages:
  - clone
  - build
  - test
  - publish