app:
  name: oAuth API
  ui_host: http://localhost:3000
  host: http://localhost:9000
  port: 9000
  prefix: ''
  cors:
    allowMethods:
      - GET
      - HEAD
      - PUT
      - POST
      - DELETE
      - PATCH
      - OPTIONS
    credentials: true

log:
  level: debug

google:
  clientId: your-google-client-id
  clientSecret: your-google-client-secret

facebook:
  apiVersion: v7.0
  id: your-facebook-id
  secret: your-facebook-secret
  token: your-facebook-token

untappd:
  host: https://api.untappd.com/v4
  clientId: untappd-client-id
  clientSecret: untappd-client-secret

stripe:
  apiKey: stripe-api-key

database:
  client: pg
  connectionTimeout: 10000
  connection:
    # filename: ./test/testdb.sqlite
    host: localhost
    port: 5432
    user: hopcoop
    password: root
    database: hopcoop
  pool:
    min: 1
    max: 2
  migrations:
    directory: src/database/migs
    extension: ts
    tableName: knex_oauth_migs
    loadExtensions: 
      - .ts
      - .js
  seeds:
    directory: src/database/seeds

crypto:
  secret: pacopaco

jwt:
  secret: pacopaco
  durationSecs: 3600
  refreshDurationSecs: 86400
  resetDurationSecs: 86400

cookie:
  keys:
    - pacopaco
    - paco
  opts:
    signed: true
    path: /
    httpOnly: true
    secure: false
    overwrite: true
    sameSite: true

pubsub:
  opts:
    projectId: project-id
    apiEndpoint: localhost:8085
  topic: mail.generate